Task 4: encryption
mw6969/MentoringProgram pull request #5
Opened 2024-06-30 19:02 UTC by mw6969

2024-07-16 07:22 UTC, SRyabinin requested changes

2024-07-16 07:22 UTC, SRyabinin commented on src/Session.cpp
> +          const auto test = Cryptor::getSha256Hash(fileName_);
Сервер пишет данные в файл с именем `Utils::getUniqueFileName(fileName_)`, хеш это файла нужно проверять с кэшом исходного файла. Тут же в лучшем случае второй раз вычисляется кэш исходного файла, это если server и client используют одну рабочую директорию. У меня сервер работает в разных директориях и исходный файл тут просто не находится, сервер падает без каких либо сообщений об ошибке. В логе только непонятная ошибка:
2024-07-01 12:07:51 Failed to open file: 2.jpg

2024-07-16 07:22 UTC, SRyabinin commented on src/Client.cpp
> +  CryptoPP::byte publicKey[CryptoPP::AES::DEFAULT_KEYLENGTH];
На сколько я понимаю тут используется симметричное шифрование - один ключ и для шифрования и для расшифрации.  То что ключ называется публичным вводит в заблуждение. Публичные ключи это про ассиметричное шифрование с public и private ключами.
По сути в текущей реализации нет никакой защиты. Ключ сгенерированный клиентом отправлятся по незащищенному каналу серверу. В случае атаки man in the middle протокол будет так же легко взломан и вся передача файлов дешифрована.
Так же без труда любой пользователь может подключиться к серверу при помощи клиента и залить файлы. 
Приведу еще раз миниальный случай, безопасность которого необходимо обеспечить:
Представь, ты запустил сервер дома и хочешь безопасно засылать себе файлики с работы. А я запустил у себя свою копию сервера и тоже хочу слать файлы себе. При этом если я случайно подключюсь к твоему серверу и зашлю файл тебе, ты не должен его дешифровать.

2024-07-18 11:42 UTC, mw6969 commented on src/Session.cpp
> +          const auto test = Cryptor::getSha256Hash(fileName_);
Обновлено.

2024-07-18 11:42 UTC, mw6969 commented on src/Client.cpp
> +  CryptoPP::byte publicKey[CryptoPP::AES::DEFAULT_KEYLENGTH];
Обновлено.

2024-09-06 10:41 UTC, SRyabinin commented on src/Client.cpp
> +      (CryptoPP::AES::BLOCKSIZE - (size % CryptoPP::AES::BLOCKSIZE)) !=
В левой и правой частях неравенства присутствует `CryptoPP::AES::BLOCKSIZE`. Выражение можно сократить до `const bool hasPadding = size % CryptoPP::AES::BLOCKSIZE != 0`

2024-09-06 10:41 UTC, SRyabinin commented on src/Client.cpp
> +      memcpy(buf + sizeof(buf) - paddingLength, garbage.c_str(), paddingLength);
Для заполнения памяти заданным значение есть стандартная функция [memset](https://cplusplus.com/reference/cstring/memset)
Но тут вообще не нужно ничего заполнять. Читатель в любом случае отбрасывает эту часть буфера.

2024-09-06 10:41 UTC, SRyabinin commented on src/Client.cpp
> +    CryptoPP::byte encryptedBuf[sizeof(buf)];
Вариант с padding работает. Однако есть альтернативное решение с формулой выравнивания размера буфера, что бы он стал кратен заданному значению.  Если нам известно, что выравнивание `CryptoPP::AES::BLOCKSIZE` для читателя и писателя одинаковые = 16 байт, то можно реализовать вообще без паддинга. Передать на сервер часный размер файла. Чтобы вычислить leftToRead использовать формулу выравнивания:
`const auto leftToRead = ((fileSize+ CryptoPP::AES::BLOCKSIZE - 1) / CryptoPP::AES::BLOCKSIZE) * CryptoPP::AES::BLOCKSIZE`

Аналогично в этом месте всегда выравнивать length, чтобы он стал кратным 16 по той же формуле:
`const auto newLength = ((length + CryptoPP::AES::BLOCKSIZE - 1) / CryptoPP::AES::BLOCKSIZE) * CryptoPP::AES::BLOCKSIZE`

2024-09-06 10:41 UTC, SRyabinin commented on src/Session.cpp
> +          if ((leftToRead_ - length <= 0) && (paddingLength_ > 0)) {
По моему тут смешана логика и проверка на ошибки. 
я бы добавил 
`assert(leftToRight_ >= length)` 
Ну а для продакшен реализации исключение, если нам прислали данных больше, чем мы ожидаем.
Тогда, чтобы использовать паддин, достаточно проверить, что пришел последний блок:
```
const auto padding = leftToRead == length ? paddingLength_ : 0;
outputFile_.write(reinterpret_cast<const char *>(decryptedBuf), length - padding);
```
проверять, что paddingLength_ не нулевой смысла особого нет, он на результат не повлияет.

2024-10-17 14:32 UTC, mw6969 commented on src/Client.cpp
> +      (CryptoPP::AES::BLOCKSIZE - (size % CryptoPP::AES::BLOCKSIZE)) !=
Обновлено.

2024-10-17 14:33 UTC, mw6969 commented on src/Client.cpp
> +      memcpy(buf + sizeof(buf) - paddingLength, garbage.c_str(), paddingLength);
Обновлено.

2024-10-17 14:33 UTC, mw6969 commented on src/Session.cpp
> +          if ((leftToRead_ - length <= 0) && (paddingLength_ > 0)) {
Обновлено.

2024-10-18 10:24 UTC, mw6969 commented on src/Client.cpp
> +    CryptoPP::byte encryptedBuf[sizeof(buf)];
Я не понял как это реализовать. Если сделать без падинга, то как сервер узнает, что последний блок имеет падинг? Поэтому пока оставил свое решение.

2024-10-18 10:30 UTC, merged